#document settings
title: Open Data Appendix
description: Office of Management and Budgets
url: http://project-open-data.github.com/
repo_url: https://github.com/project-open-data/project-open-data.github.com

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true